#include <iostream>
#include <random>

#include "random.hpp"

using namespace WarGrey::STEM;

/*************************************************************************************************/
// Members in <random> override the operator '()' to generate value

// non-determinstic generator
static std::random_device rd;

// to seed mersenne twister, similar to srand() with datum better than time(nullptr);
static std::mt19937 random_generator(rd());

/*************************************************************************************************/
int WarGrey::STEM::random_raw() {
    return random_generator();
}

int WarGrey::STEM::random_uniform(int min, int max) {
    // shape data generated by a generator with a distribution for integers in [min, max] 
    std::uniform_int_distribution<> random_dist(min, max);


    return random_dist(random_generator);
}
